# Generated by Django 5.0.1 on 2024-01-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigo_produto', models.CharField(max_length=200)),
                ('descricao_produto', models.TextField(blank=True, null=True)),
                ('preco_produto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
