# Generated by Django 5.0.1 on 2024-01-15 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='nome',
            new_name='nome_produto',
        ),
    ]
